"""add listener control table

Revision ID: 34f9903299d5
Revises: c4ff94b64d59
Create Date: 2026-09-21 13:12:42.071702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f9903299d5'
down_revision: Union[str, Sequence[str], None] = 'c4ff94b64d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reload_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reload_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sources_loaded', sa.Integer(), nullable=True),
    sa.Column('last_rules_loaded', sa.Integer(), nullable=True),
    sa.Column('last_recipients_loaded', sa.Integer(), nullable=True),
    sa.Column('last_new_matches', sa.Integer(), nullable=True),
    sa.Column('last_scan_failures', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('applied_config_hash', sa.String(length=64), nullable=True),
    sa.Column('listener_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listener_control')
    # ### end Alembic commands ###
