"""add active flag to source and recipient

Revision ID: 9d7fe3cea8f6
Revises: dd3b694df829
Create Date: 2026-09-11 20:17:01.798050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7fe3cea8f6'
down_revision: Union[str, Sequence[str], None] = 'dd3b694df829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
